### ISSUE TITLE
Wont play music 

### ISSUE THREAD

**Issue by tomokoNALS** [Codeusa/aurous-app#16]
java.lang.NullPointerException
	at me.aurous.utils.media.MediaUtils.lambda$0(MediaUtils.java:390)
	at me.aurous.utils.media.MediaUtils$$Lambda$97/23423523.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$86/20867685.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$85/17377432.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$50/26578260.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Codeusa** [comment]
What track are you trying to play (url)?

**Comment by Codeusa** [comment]
The decryption scripts seems to have broken, I will fix this shortly.

**Comment by keyboardN1nja** [comment]
I just found Aurous and was about to report this exact issue. Also, I got two exceptions:
```
java.lang.NullPointerException
	at me.aurous.utils.media.MediaUtils.lambda$0(MediaUtils.java:390)
	at me.aurous.utils.media.MediaUtils$$Lambda$93/27163889.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$86/12906966.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$85/2890491.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$50/20354131.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
```
java.lang.NullPointerException
	at me.aurous.player.scenes.MediaPlayerScene.createMediaPlayer(MediaPlayerScene.java:36)
	at me.aurous.utils.media.MediaUtils.lambda$0(MediaUtils.java:384)
	at me.aurous.utils.media.MediaUtils$$Lambda$93/27163889.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$86/12906966.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$85/2890491.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$50/20354131.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Codeusa** [comment]
I've pushed an update that resolves this issue, seems my regex was invalid. Do let me know if it works now.

**Comment by keyboardN1nja** [comment]
Working now, thanks!

**Comment by Codeusa** [comment]
Thanks for using it! Feel free to leave any feedback or suggestions for code implementation.
