### ISSUE TITLE
I get this error every time I try and play a song in aurous :(

### ISSUE THREAD

**Issue by Orrison** [Codeusa/aurous-app#17]
java.lang.NullPointerException
	at me.aurous.utils.media.MediaUtils.lambda$0(MediaUtils.java:390)
	at me.aurous.utils.media.MediaUtils$$Lambda$88/30922765.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$79/17836119.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(Unknown Source)
	at com.sun.javafx.application.PlatformImpl$$Lambda$78/21998695.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$141(Unknown Source)
	at com.sun.glass.ui.win.WinApplication$$Lambda$43/120101.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Codeusa** [comment]
I've pushed an update to fix this, try restarting Aurous and let me know.

**Comment by Orrison** [comment]
All good now :) I just have to say how crazy awesome you are! I just 
discovered your work and all of it is amazing and ground breaking. Thank 
you :D
------ Original Message ------
