### ISSUE TITLE
exception to find decrypt.js file

### ISSUE THREAD

**Issue by bberry59** [Codeusa/aurous-app#22]
When I try to play a track from my youtube list, I have often this exception (I use the app on linux version) : 
**java.io.FileNotFoundException: ./data/scripts/decrypt.js (Aucun fichier ou dossier de ce type)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at me.aurous.services.impl.YouTubeService.signDecipher(YouTubeService.java:280)
	at me.aurous.services.impl.YouTubeService.extractURLS(YouTubeService.java:260)
	at me.aurous.services.impl.YouTubeService.grab(YouTubeService.java:170)
	at me.aurous.utils.media.MediaUtils.getMediaURL(MediaUtils.java:182)
	at me.aurous.player.scenes.RemoteMediaScene.createMediaPlayer(RemoteMediaScene.java:35)
	at me.aurous.utils.media.MediaUtils.lambda$0(MediaUtils.java:383)
	at me.aurous.utils.media.MediaUtils$$Lambda$86/1599580455.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$85/1953480156.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$84/174147555.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$47/1915857050.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)**

or 
this one 
**java.lang.UnsupportedOperationException: Unsupported protocol "https"
	at com.sun.media.jfxmedia.locator.Locator.<init>(Locator.java:233)
	at javafx.scene.media.Media.<init>(Media.java:391)
	at me.aurous.player.scenes.RemoteMediaScene.createMediaPlayer(RemoteMediaScene.java:37)
	at me.aurous.utils.media.MediaUtils.lambda$0(MediaUtils.java:383)
	at me.aurous.utils.media.MediaUtils$$Lambda$86/1256407705.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$85/1763932429.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$84/1982277392.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$47/1370887930.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)**

**Comment by Codeusa** [comment]
This will be fixed in the new version; we're currently rewriting the entire application.

**Comment by bberry59** [comment]
ok, I stay tuned !
